# Generated by Django 4.2.7 on 2025-04-20 07:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ticket.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('cnic_number', models.CharField(max_length=20)),
                ('related_to', models.CharField(blank=True, help_text='Name of primary CNIC holder if using shared CNIC', max_length=255, null=True)),
                ('relationship', models.CharField(choices=[('self', 'Self'), ('parent', 'Parent'), ('child', 'Child'), ('spouse', 'Spouse'), ('sibling', 'Sibling'), ('other', 'Other')], default='self', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_type', models.CharField(choices=[('Gwader End', 'Gwader End'), ('Chaman End', 'Chaman End')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('unscanned', 'Unscanned'), ('scanned_gate1', 'Scanned at Gate 1'), ('scanned_both', 'Scanned at Both Gates'), ('tampered', 'Tampered')], default='unscanned', max_length=20)),
                ('is_tampered', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=ticket.models.qr_code_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='ticket.ticketuser')),
            ],
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gate', models.CharField(choices=[('gate1', 'Gate 1 (Entry)'), ('gate2', 'Gate 2 (Exit)')], max_length=10)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='ticket.ticket')),
            ],
            options={
                'unique_together': {('ticket', 'gate')},
            },
        ),
    ]
