# Generated by Django 4.2.7 on 2025-04-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Gawader Enclosure', 'Gawader Enclosure'), ('Chaman Enclosure', 'Chaman Enclosure')], max_length=20),
        ),
    ]
