# Generated by Django 4.2.7 on 2025-04-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_ticketquota_alter_scanlog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('Gwadar Enclosure', 'Gwadar Enclosure'), ('Chaman Enclosure', 'Chaman Enclosure')], max_length=50),
        ),
    ]
